"""empty message

Revision ID: 08416b00b045
Revises: f72d8a793f16
Create Date: 2020-01-03 22:00:35.873328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08416b00b045'
down_revision = 'f72d8a793f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_journey_step', sa.Column('ua_browser', sa.String(), nullable=True))
    op.add_column('user_journey_step', sa.Column('ua_language', sa.String(), nullable=True))
    op.add_column('user_journey_step', sa.Column('ua_platform', sa.String(), nullable=True))
    op.add_column('user_journey_step', sa.Column('ua_string', sa.String(), nullable=True))
    op.add_column('user_journey_step', sa.Column('ua_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_journey_step', 'ua_version')
    op.drop_column('user_journey_step', 'ua_string')
    op.drop_column('user_journey_step', 'ua_platform')
    op.drop_column('user_journey_step', 'ua_language')
    op.drop_column('user_journey_step', 'ua_browser')
    # ### end Alembic commands ###
