"""empty message

Revision ID: 4786fb9ce0b9
Revises: f6555ef71dcd
Create Date: 2020-02-02 15:52:50.906256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4786fb9ce0b9'
down_revision = 'f6555ef71dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_seconds', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('liste', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('twitter_liste', sa.String(), nullable=True),
    sa.Column('twitter_tete_de_liste', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('survey', sa.Column('created_seconds', sa.Integer(), nullable=True))
    op.add_column('survey', sa.Column('updated_seconds', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'survey', ['name'])
    op.add_column('survey_question', sa.Column('created_seconds', sa.Integer(), nullable=True))
    op.add_column('survey_question', sa.Column('updated_seconds', sa.Integer(), nullable=True))
    op.drop_column('survey_question', 'created_microseconds')
    op.drop_column('survey_question', 'updated_microseconds')
    op.add_column('survey_responder', sa.Column('created_seconds', sa.Integer(), nullable=True))
    op.add_column('survey_responder', sa.Column('updated_seconds', sa.Integer(), nullable=True))
    op.drop_column('survey_responder', 'created_microseconds')
    op.drop_column('survey_responder', 'updated_microseconds')
    op.add_column('survey_response', sa.Column('created_seconds', sa.Integer(), nullable=True))
    op.add_column('survey_response', sa.Column('survey_target_id', sa.Integer(), nullable=True))
    op.add_column('survey_response', sa.Column('updated_seconds', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey_response', 'survey_target', ['survey_target_id'], ['id'])
    op.drop_column('survey_response', 'created_microseconds')
    op.drop_column('survey_response', 'updated_microseconds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_response', sa.Column('updated_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('survey_response', sa.Column('created_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'survey_response', type_='foreignkey')
    op.drop_column('survey_response', 'updated_seconds')
    op.drop_column('survey_response', 'survey_target_id')
    op.drop_column('survey_response', 'created_seconds')
    op.add_column('survey_responder', sa.Column('updated_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('survey_responder', sa.Column('created_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('survey_responder', 'updated_seconds')
    op.drop_column('survey_responder', 'created_seconds')
    op.add_column('survey_question', sa.Column('updated_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('survey_question', sa.Column('created_microseconds', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('survey_question', 'updated_seconds')
    op.drop_column('survey_question', 'created_seconds')
    op.drop_constraint(None, 'survey', type_='unique')
    op.drop_column('survey', 'updated_seconds')
    op.drop_column('survey', 'created_seconds')
    op.drop_table('survey_target')
    # ### end Alembic commands ###
