"""empty message

Revision ID: 58e46f6aba67
Revises: c8cf39723040
Create Date: 2020-01-05 14:31:26.782102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e46f6aba67'
down_revision = 'c8cf39723040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_journey_step', sa.Column('is_entry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_journey_step', 'is_entry')
    # ### end Alembic commands ###
