"""empty message

Revision ID: 8bed36f1c01d
Revises: 9b7c3502ac0c
Create Date: 2020-01-05 18:28:19.791702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bed36f1c01d'
down_revision = '9b7c3502ac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responder', sa.Column('parti_rattaches', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responder', 'parti_rattaches')
    # ### end Alembic commands ###
