"""empty message

Revision ID: 9b7c3502ac0c
Revises: 58e46f6aba67
Create Date: 2020-01-05 16:34:28.389655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7c3502ac0c'
down_revision = '58e46f6aba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('question_title', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_responder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('liste', sa.String(), nullable=True),
    sa.Column('parti_principal', sa.String(), nullable=True),
    sa.Column('tete_de_liste', sa.String(), nullable=True),
    sa.Column('sortant', sa.Boolean(), nullable=True),
    sa.Column('email_liste', sa.String(), nullable=True),
    sa.Column('email_person', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('twitter_liste', sa.String(), nullable=True),
    sa.Column('twitter_candidat', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('survey_question_id', sa.Integer(), nullable=False),
    sa.Column('survey_responder_id', sa.Integer(), nullable=False),
    sa.Column('survey_question_response', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['survey_question_id'], ['survey_question.id'], ),
    sa.ForeignKeyConstraint(['survey_responder_id'], ['survey_responder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_response')
    op.drop_table('survey_responder')
    op.drop_table('survey_question')
    op.drop_table('survey')
    # ### end Alembic commands ###
