"""empty message

Revision ID: b4efe7c1d3ed
Revises: 4786fb9ce0b9
Create Date: 2020-02-05 15:35:06.866227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4efe7c1d3ed'
down_revision = '4786fb9ce0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_target', sa.Column('tete_de_liste', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_target', 'tete_de_liste')
    # ### end Alembic commands ###
