"""empty message

Revision ID: c8cf39723040
Revises: 08416b00b045
Create Date: 2020-01-04 18:06:01.093591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cf39723040'
down_revision = '08416b00b045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_journey_step', sa.Column('ip_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_journey_step', 'ip_hash')
    # ### end Alembic commands ###
