"""empty message

Revision ID: e3360b27f762
Revises: 
Create Date: 2020-01-08 12:46:53.261120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3360b27f762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tn_schema'
    )
    op.create_table('user_journey_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('is_entry', sa.Boolean(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('referrer_host', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('this_page_url', sa.String(), nullable=True),
    sa.Column('this_page_canonical', sa.String(), nullable=True),
    sa.Column('geo_country', sa.String(), nullable=True),
    sa.Column('geo_region', sa.String(), nullable=True),
    sa.Column('geo_city', sa.String(), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('screen_resolution', sa.Integer(), nullable=True),
    sa.Column('ua_string', sa.String(), nullable=True),
    sa.Column('ua_browser', sa.String(), nullable=True),
    sa.Column('ua_language', sa.String(), nullable=True),
    sa.Column('ua_platform', sa.String(), nullable=True),
    sa.Column('ua_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tn_schema'
    )
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('question_title', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['tn_schema.survey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tn_schema'
    )
    op.create_table('survey_responder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('liste', sa.String(), nullable=True),
    sa.Column('parti_principal', sa.String(), nullable=True),
    sa.Column('parti_rattaches', sa.String(), nullable=True),
    sa.Column('tete_de_liste', sa.String(), nullable=True),
    sa.Column('sortant', sa.Boolean(), nullable=True),
    sa.Column('email_liste', sa.String(), nullable=True),
    sa.Column('email_person', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('twitter_liste', sa.String(), nullable=True),
    sa.Column('twitter_candidat', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['tn_schema.survey.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tn_schema'
    )
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('updated_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('survey_question_id', sa.Integer(), nullable=False),
    sa.Column('survey_responder_id', sa.Integer(), nullable=False),
    sa.Column('survey_question_response', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['tn_schema.survey.id'], ),
    sa.ForeignKeyConstraint(['survey_question_id'], ['tn_schema.survey_question.id'], ),
    sa.ForeignKeyConstraint(['survey_responder_id'], ['tn_schema.survey_responder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tn_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_response', schema='tn_schema')
    op.drop_table('survey_responder', schema='tn_schema')
    op.drop_table('survey_question', schema='tn_schema')
    op.drop_table('user_journey_step', schema='tn_schema')
    op.drop_table('survey', schema='tn_schema')
    # ### end Alembic commands ###
