"""empty message

Revision ID: f6555ef71dcd
Revises: e67a3d912dac
Create Date: 2020-01-19 21:22:10.656356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6555ef71dcd'
down_revision = 'e67a3d912dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.BigInteger(), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.Column('validation_token', sa.String(length=120), nullable=True),
    sa.Column('validation_expiry_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
