"""empty message

Revision ID: f72d8a793f16
Revises: 
Create Date: 2020-01-01 19:43:46.776498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72d8a793f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_journey_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('referrer_host', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('this_page_url', sa.String(), nullable=True),
    sa.Column('this_page_canonical', sa.String(), nullable=True),
    sa.Column('geo_country', sa.String(), nullable=True),
    sa.Column('geo_region', sa.String(), nullable=True),
    sa.Column('geo_city', sa.String(), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('screen_resolution', sa.Integer(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_journey_step')
    # ### end Alembic commands ###
